# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f45d7973fd1f377a8e8e3a61029daa32ee274c1e17e7b5c9cc64596a006d3a62cc0167f034f2fb9d8a3c66d27177240a45da5acee12e4dddedfc324143fa62

test:
  secret_key_base: b549231e5ede37d3795e1029b194c799d4c5e8448caa8c752e8bb9cb3e3f90bb89f5a17df2b82a88dfbe09ffeb58454763fd47f31eda54eb1bf6f309a9dd21fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
